name: AH Update

on:
  workflow_dispatch:
    inputs:
      compress_all:
        description: 'compress all records'
        required: false
        type: boolean
        default: false

  schedule:
  # 12 times a day
  - cron: '0 */2 * * *'


jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload-coverage: false

  ah_update:
    runs-on: ubuntu-latest
    environment: env_main
    permissions:
      contents: write
    needs: test
    steps:
    # checkout 'latest' tag
    - uses: actions/checkout@v3
      with:
        ref: latest
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set up environment variables
      run: |
        echo "JOB_START_TS=$(date +%s)" >> $GITHUB_ENV
        echo "DB_PATH=/tmp/ah_db" >> $GITHUB_ENV
    - name: Get AH Database File from GitHub Cache
      uses: actions/cache@v3
      with:
        path: ${{ env.DB_PATH }}
        # save cache, caches are evicted after 7 days 
        # or by ascending access time if over 10GB
        # https://github.com/actions/cache/issues/2#issuecomment-548426628
        key: ${{ runner.os }}-ah-${{ env.JOB_START_TS }}
        # load most recently created cache
        restore-keys: |
          ${{ runner.os }}-ah-
    - name: Run AH Update
      env:
        BN_CLIENT_ID: ${{ secrets.BN_CLIENT_ID }}
        BN_CLIENT_SECRET: ${{ secrets.BN_CLIENT_SECRET }}
      run: >
        printf %s\\n 
        retail tw classic tw classic_wlk tw 
        retail kr classic kr classic_wlk kr 
        classic us classic eu |
        xargs -n2 
        python -m ah.updater 
        ${{ inputs.compress_all && '--compress_all ' || ' ' }}
        --db_path ${{ env.DB_PATH }} 
        --game_version 
    - name: Release DB - TW
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: |
          ${{ env.DB_PATH }}/*tw*.gz
          ${{ env.DB_PATH }}/*tw*.bin
          ${{ env.DB_PATH }}/*tw*.json
        name: DB ${{ env.JOB_START_TS }}
    - name: Reset Rate Limit (sleep 1 minute)
      run: sleep 60
    - name: Release DB - KR
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: |
          ${{ env.DB_PATH }}/*kr*.gz
          ${{ env.DB_PATH }}/*kr*.bin
          ${{ env.DB_PATH }}/*kr*.json
        name: DB ${{ env.JOB_START_TS }}
    - name: Reset Rate Limit (sleep 1 minute)
      run: sleep 60
    - name: Release DB - US & EU
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: |
          ${{ env.DB_PATH }}/*us*.gz
          ${{ env.DB_PATH }}/*us*.bin
          ${{ env.DB_PATH }}/*us*.json
          ${{ env.DB_PATH }}/*eu*.gz
          ${{ env.DB_PATH }}/*eu*.bin
          ${{ env.DB_PATH }}/*eu*.json
        name: DB ${{ env.JOB_START_TS }}
      