name: Cron Jobs

on:
  workflow_dispatch:
  schedule:
  # every hour
  - cron: '0 * * * *'

jobs:
  get_hour:
    runs-on: ubuntu-latest
    steps:
      - name: Get current hour
        id: current_hour
        run: |
          hour=$(date +'%H')
          remainder=$((hour % 3))
          echo "::set-output name=remainder::${remainder}"

  ah_tw:
    if: ${{ steps.current_hour.outputs.remainder == 0 }}
    uses: ./.github/workflows/ah.yml
    with:
      xargs: retail tw classic tw classic_wlk tw
      upload_glob: '*tw*'
    
  ah_kr:
    if: ${{ steps.current_hour.outputs.remainder == 1 }}
    uses: ./.github/workflows/ah.yml
    with:
      xargs: retail kr classic kr classic_wlk kr
      upload_glob: '*kr*'

  ah_us_eu:
    if: ${{ steps.current_hour.outputs.remainder == 2 }}
    timeout-minutes: 50
    strategy:
      max-parallel: 1
      matrix:
        include:
          - xargs: classic us
            upload_glob: '*us*'
          - xargs: classic eu
            upload_glob: '*eu*'
    steps:
      - uses: ./.github/workflows/ah.yml
        with:
          xargs: ${{ matrix.xargs }}
          upload_glob: ${{ matrix.upload_glob }}
    