name: Cron Jobs

on:
  workflow_dispatch:
  schedule:
  # every hour
  - cron: '0 * * * *'

jobs:
  get_hour:
    runs-on: ubuntu-latest
    outputs:
      remainder: ${{ steps.hour_modulo.outputs.remainder }}
    steps:
      - name: Get Hour Modulo 3
        id: hour_modulo
        run: |
          hour=$(date +'%H')
          remainder=$((hour % 3))
          echo "remainder=${remainder}" >> $GITHUB_OUTPUT

  ah_tw:
    runs-on: ubuntu-latest
    needs: get_hour
    if: ${{ needs.get_hour.outputs.remainder == 0 }}
    environment: env_main
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/ah.yml
      with:
        xargs: retail tw classic tw classic_wlk tw
        upload_glob: '*tw*'
        secrets: inherit
    
  ah_kr:
    runs-on: ubuntu-latest
    needs: get_hour
    if: ${{ needs.get_hour.outputs.remainder == 1 }}
    environment: env_main
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/ah.yml
      with:
        xargs: retail kr classic kr classic_wlk kr
        upload_glob: '*kr*'
        secrets: inherit


  ah_us_eu:
    runs-on: ubuntu-latest
    needs: get_hour
    if: ${{ needs.get_hour.outputs.remainder == 2 }}
    environment: env_main
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
        - xargs: classic us
          upload_glob: '*us*'
        - xargs: classic eu
          upload_glob: '*eu*'
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/ah.yml
      with:
        xargs: ${{ matrix.xargs }}
        upload_glob: ${{ matrix.upload_glob }}
        secrets: inherit