name: Cron Jobs

on:
  workflow_dispatch:
  schedule:
  # every hour
  - cron: '0 * * * *'

jobs:
  get_hour:
    runs-on: ubuntu-latest
    outputs:
      remainder: ${{ steps.hour_modulo.outputs.remainder }}
    steps:
      - name: Get Hour Modulo 3
        id: hour_modulo
        run: |
          hour=$(date +'%H')
          remainder=$((hour % 3))
          echo "::set-output name=remainder::${remainder}"

  ah_tw:
    uses: ./.github/workflows/ah.yml
    if: ${{ needs.get_hour.outputs.remainder == 0 }}
    needs: get_hour
    with:
      xargs: retail tw classic tw classic_wlk tw
      upload_glob: '*tw*'
    
  ah_kr:
    uses: ./.github/workflows/ah.yml
    if: ${{ needs.get_hour.outputs.remainder == 1 }}
    needs: get_hour
    with:
      xargs: retail kr classic kr classic_wlk kr
      upload_glob: '*kr*'

  ah_us_eu:
    uses: ./.github/workflows/ah.yml
    if: ${{ needs.get_hour.outputs.remainder == 2 }}
    needs: get_hour
    strategy:
      max-parallel: 1
      matrix:
        include:
          - xargs: classic us
            upload_glob: '*us*'
          - xargs: classic eu
            upload_glob: '*eu*'
    with:
      xargs: ${{ matrix.xargs }}
      upload_glob: ${{ matrix.upload_glob }}
    